name: Build LaTeX document
on:
  push:
    paths:
      - 'Alembic.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
         root_file: Alembic.tex
      - name: Update README
        uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - run: php buildtools/buildreadme.php
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: LaTexCompiler
          message: 'Compiled LaTeX into PDF, updated README'
          add: '*'
